name: Create Repo With Readme And Protection

on:
  push:
    branches: [ main ]

env:
  REVIEWER_COUNT: 2
#  REPO_NAME: "${{ github.event.inputs.repo-name }}"
  ORG_NAME: "${{ secrets.ORGANIZATION }}"

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Repository with branch protection
        run: |     
          ORG_NAME="${{ secrets.ORGANIZATION }}"
          
          curl --location --request PUT 'https://api.github.com/repos/$ORG_NAME/jo/branches/main/protection' \
              --header 'Accept: application/vnd.github.luke-cage-preview+json' \
              --header 'Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}' \
              --header 'Content-Type: application/json' \
              --data-raw '{
              "required_status_checks": null, 
              "enforce_admins": true, 
              "required_pull_request_reviews": 
              {
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": ${{env.REVIEWER_COUNT}}
              }, 
              "restrictions": null
              }'
