name: Create Default README

on:
  push:
    branches:
      - main

jobs:
  create-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create README
      run: echo "# My Project" >> README.md

    - name: Commit and push changes
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add README.md
        git commit -m "Create default README"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
